#line 2 "lexer.C"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
static yyconst short int yy_acclist[437] =
    {   0,
      101,   99,  100,   15,   99,  100,   15,  100,   97,   99,
      100,   99,  100,   99,  100,   98,   99,  100,   97,   99,
      100,   97,   99,  100,   99,  100,   97,   99,  100,   97,
       99,  100,   97,   99,  100,   97,   99,  100,   97,   99,
      100,   97,   99,  100,   21,   99,  100,   19,   99,  100,
       97,   99,  100,   97,   99,  100,   97,   99,  100,   97,
       99,  100,   98,   99,  100,   98,   99,  100,   98,   99,
      100,   98,   99,  100,   98,   99,  100,   98,   99,  100,
       98,   99,  100,   98,   99,  100,   98,   99,  100,   98,
       99,  100,   98,   99,  100,   98,   99,  100,   98,   99,

      100,   98,   99,  100,   98,   99,  100,   97,   99,  100,
        4,  100,    5,  100,    4,  100,    4,  100,    9,  100,
       10,  100,    9,  100,    9,  100,    9,  100,    9,  100,
       15,   96,   25,   98,   82,   91,   83,   80,   89,   78,
       90,   79,   24,   11,   14,   81,   24,   21,   24,   23,
       18,   19,   16,   88,   93,   95,   94,   86,   84,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   36,   98,
       98,   98,   98,   98,   98,   98,   45,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   85,   92,    3,

        2,    7,    6,   22,   13,   14,   24,   24,   20,   77,
       75,   87,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   44,   98,
       98,   98,   49,   98,   98,   98,   53,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   71,   98,   98,   98,   98,   24,   12,
       17,   76,   98,   98,   98,   29,   98,   30,   98,   98,
       32,   98,   98,   98,   98,   98,   38,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   51,   98,   98,   54,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,

       98,   65,   98,   98,   98,   70,   98,   72,   98,   98,
       98,   74,   98,   98,   28,   98,   31,   98,   33,   98,
       98,   98,   98,   98,   40,   98,   41,   98,   43,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       60,   98,   98,   62,   98,   98,   98,   67,   98,   98,
       98,   73,   98,   98,   98,   98,   98,   37,   98,   98,
       98,   98,   47,   98,   98,   98,   52,   98,   98,   98,
       98,   58,   98,   59,   98,   61,   98,   63,   98,   98,
       68,   98,   98,   98,    1,   98,   27,   98,   98,   35,
       98,   39,   98,   42,   98,   98,   98,   98,   55,   98,

       56,   98,   98,   98,   98,   98,   26,   98,   34,   98,
       98,   98,   98,   98,   98,   98,   66,   98,   98,   98,
       50,   98,   57,   98,   98,   69,   98,   46,   98,   48,
       98,   98,   98,   64,   98,    8
    } ;

static yyconst short int yy_accept[373] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   14,   16,   19,   22,   25,   27,   30,   33,
       36,   39,   42,   45,   48,   51,   54,   57,   60,   63,
       66,   69,   72,   75,   78,   81,   84,   87,   90,   93,
       96,   99,  102,  105,  108,  111,  113,  115,  117,  119,
      121,  123,  125,  127,  129,  131,  132,  133,  133,  134,
      134,  134,  135,  136,  137,  138,  138,  138,  139,  140,
      141,  142,  143,  143,  144,  144,  145,  146,  147,  148,
      149,  149,  150,  150,  151,  152,  152,  153,  154,  155,
      156,  157,  158,  159,  160,  161,  162,  163,  164,  165,

      166,  167,  168,  169,  171,  172,  173,  174,  175,  176,
      177,  179,  180,  181,  182,  183,  184,  185,  186,  187,
      188,  189,  190,  191,  192,  193,  194,  195,  196,  197,
      198,  199,  200,  201,  202,  203,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  205,  205,  205,  205,  205,
      205,  206,  207,  208,  208,  209,  210,  211,  212,  213,
      214,  215,  216,  217,  218,  219,  220,  221,  222,  223,
      224,  225,  226,  227,  228,  229,  231,  232,  233,  235,
      236,  237,  239,  240,  241,  242,  243,  244,  245,  246,
      247,  248,  249,  250,  251,  252,  253,  254,  256,  257,

      258,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      260,  260,  261,  262,  263,  264,  265,  266,  268,  270,
      271,  273,  274,  275,  276,  277,  279,  280,  281,  282,
      283,  284,  285,  286,  287,  289,  290,  292,  293,  294,
      295,  296,  297,  298,  299,  300,  301,  302,  304,  305,
      306,  308,  310,  311,  312,  312,  312,  312,  312,  313,
      314,  315,  317,  319,  321,  322,  323,  324,  325,  327,
      329,  331,  332,  333,  334,  335,  336,  337,  338,  339,
      340,  341,  343,  344,  346,  347,  348,  350,  351,  352,
      354,  354,  354,  354,  354,  354,  354,  355,  356,  357,

      358,  360,  361,  362,  363,  365,  366,  367,  369,  370,
      371,  372,  374,  376,  378,  380,  381,  383,  384,  385,
      385,  385,  386,  386,  386,  386,  387,  389,  390,  392,
      394,  396,  397,  398,  399,  401,  403,  404,  405,  406,
      407,  407,  407,  407,  409,  411,  412,  413,  414,  415,
      416,  417,  419,  419,  419,  420,  421,  423,  425,  426,
      428,  428,  428,  430,  432,  433,  433,  434,  434,  436,
      437,  437
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       12,   13,   14,   12,   15,   16,   17,   18,   19,   19,
       19,   20,   20,   20,   20,   21,   21,   12,   12,   22,
       23,   24,   12,   25,   26,   26,   26,   27,   28,   29,
        8,    8,    8,    8,    8,   30,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,   31,    8,    8,
       12,   32,   12,   33,    8,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    8,   43,   44,   45,   46,
       47,   48,    8,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   12,   58,   12,   12,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    1,    1,    1,    5,    5,    5,    5,    3,
        3,    1,    1,    5,    5,    5,    5,    5,    5,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[385] =
    {   0,
        0,    0,   56,   57,   58,   59,  689,  690,   62,   75,
      665,   61,  683,    0,  663,   58,  653,  690,  661,   66,
       67,   81,   74,  112,  152,   72,  660,   80,  659,  646,
       49,   72,   70,   63,   78,   90,  633,  100,  110,  641,
      143,   74,  631,  636,   63,  690,  690,  659,  662,  690,
      690,  657,  660,  133,  141,  107,  690,   82,  690,  157,
      134,    0,  690,  690,  690,  661,  182,  690,  690,  690,
      690,  690,  161,  217,  633,  657,    0,  690,  185,   93,
      241,  690,  196,  690,  690,    0,    0,  690,  646,  690,
      690,  690,  163,  690,  618,  620,  628,  614,  162,  630,

      629,  616,  622,  608,  609,  607,  613,  610,  608,  605,
        0,  605,  168,  606,  600,  596,  605,  612,  127,  612,
      595,  598,  610,  595,  600,  595,  178,  174,  179,  598,
      690,  690,  690,  690,  690,  690,  179,  122,  153,  602,
      233,  257,  284,  229,  690,  253,  263,  627,  273,  583,
      619,    0,    0,  222,  288,  254,  690,  690,  612,  583,
      589,  598,  593,  592,  593,  579,  577,  575,  591,  589,
      585,  584,  571,  586,  585,    0,  178,  567,  579,  576,
      573,    0,  570,  570,  559,  560,  566,  557,  559,  556,
      568,  554,  568,  553,  555,  555,  562,    0,  562,  564,

      553,  558,  192,  310,  589,  322,  339,    0,  314,  333,
      293,  690,  690,  690,  545,  555,  549,    0,    0,  550,
        0,  540,  547,  536,  543,    0,  540,  547,  540,  532,
      544,  532,  546,  530,    0,  525,    0,  543,  527,  520,
      511,  481,  478,  486,  478,  486,  480,    0,  466,  469,
        0,    0,  457,  469,  458,  355,  226,    0,  297,  471,
      466,    0,    0,    0,  453,  454,  459,  449,    0,  441,
        0,  439,  432,  432,  438,  438,  435,  413,  426,  425,
      410,    0,  419,    0,  413,  404,  398,  405,  404,    0,
      396,  377,  355,  441,  382,    0,  407,  396,  389,  389,

        0,  389,  382,  397,    0,  396,  397,    0,  392,  391,
      377,    0,    0,    0,    0,  380,    0,  388,  374,  379,
      406,  690,  401,  404,  431,  357,    0,  350,    0,    0,
        0,  340,  342,  343,    0,    0,  340,  331,  325,  331,
      332,  393,  453,    0,    0,  316,  319,  327,  327,  321,
      305,    0,  321,  475,  274,  275,    0,    0,  229,    0,
      234,  497,    0,    0,  229,  228,  194,  192,    0,  690,
      690,  536,  541,  546,  549,  554,  559,  223,  561,  183,
      566,  156,  571,   87
    } ;

static yyconst short int yy_def[385] =
    {   0,
      371,    1,  372,  372,  373,  373,  371,  371,  371,  371,
      371,  374,  371,  375,  371,  371,  376,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  374,  371,  374,
      371,  375,  371,  371,  371,  371,  376,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  377,  371,   74,   24,
      371,  371,  371,  371,  371,  378,   25,  371,  371,  371,
      371,  371,  371,  371,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      374,  374,  374,  371,  371,  371,  371,  379,  371,  371,
      371,  377,   79,  371,  371,  378,  371,  371,  371,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  371,  374,  143,  371,  371,  371,  380,  371,  371,
      371,  371,  371,  371,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  371,  143,  381,  382,  371,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      371,  143,  381,  383,  381,  384,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  371,
      383,  371,  381,  381,  381,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      371,  381,  325,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  371,  325,  375,  375,  375,  375,  375,  375,
      371,  325,  375,  375,  375,  371,  375,  371,  375,  371,
        0,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371
    } ;

static yyconst short int yy_nxt[749] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       25,   26,   27,   28,    8,   14,   14,   14,   14,   14,
       14,    8,   29,   30,   31,   32,   33,   34,   35,   14,
       14,   36,   14,   37,   14,   38,   14,   39,   40,   41,
       42,   14,   43,   44,   14,   14,   14,   45,   47,   47,
       51,   51,   54,   56,   56,   56,   59,   64,   48,   48,
       52,   55,   49,   49,   53,   53,   56,   56,   56,   69,
       65,   71,   73,   73,   73,  131,   76,   59,   70,   72,
       77,   66,   60,   89,   90,   96,   78,   97,   74,   74,

       74,   74,   92,   93,   98,   99,  105,  103,   56,   56,
       56,  107,  100,   60,  127,  101,  104,  106,  102,  108,
      132,  109,  128,  371,  110,  139,   75,   79,  111,   80,
       80,   80,   81,  115,  112,  113,  137,  116,   82,   83,
       84,   85,   86,  118,  139,  138,  140,  371,   82,   83,
       84,  117,  144,  144,  144,   85,  139,  135,  119,  371,
      296,  120,   73,   73,   73,  140,   86,   79,  185,   87,
       87,   87,   87,  186,  141,  141,  142,  140,   82,   83,
       84,   88,  137,  122,  371,  158,  159,  258,   82,   83,
       84,  138,   66,  123,  124,   88,  125,   59,  126,  146,

      146,  147,  153,  153,  153,  153,   75,  196,  143,  154,
      154,  164,  165,  155,  155,  155,  155,  178,  179,  194,
      199,  231,  200,   60,  232,  197,  195,  156,  370,  198,
      369,  294,  205,  148,   74,   74,   74,   74,   59,  155,
      155,  155,  155,   82,  149,   84,  206,  206,  206,  206,
      142,  142,  142,   82,  149,   84,   79,  295,   81,   81,
       81,   81,   59,  145,   60,  368,  367,   82,   83,   84,
      207,  207,  207,  145,  203,  203,  203,   82,   83,   84,
       66,   66,   66,  213,  366,  365,  209,  209,   60,   59,
      210,  210,  210,  210,  259,  259,  259,  213,  259,  259,

      259,  204,  204,  204,  204,  155,  155,  155,  155,  204,
      204,  204,  204,  364,   82,   60,   84,  204,  204,  204,
      204,  204,  204,  363,   82,  205,   84,  256,  256,  256,
      256,  210,  210,  210,  210,  256,  256,  256,  256,  206,
      206,  206,  206,  256,  256,  256,  256,  256,  256,  145,
      210,  210,  210,  210,  361,  360,   66,   66,   66,   82,
      294,   84,  359,  358,  357,  356,  355,  353,  352,   82,
      351,   84,  292,  292,  292,  292,  350,  349,  348,  347,
      292,  292,  292,  292,  371,  346,  295,  345,  292,  292,
      292,  292,  292,  292,  203,  203,  203,  203,  294,  323,

      323,  324,  203,  203,  203,  203,  294,  344,  322,  294,
      203,  203,  203,  203,  203,  203,  341,  340,  324,  324,
      324,  342,  342,  342,  295,  339,  338,  337,  336,  335,
      334,  333,  295,  325,  332,  295,  294,  331,  330,  329,
      328,  327,  326,  322,  320,  319,  318,  317,  343,  343,
      343,  343,  316,  315,  314,  313,  343,  343,  343,  343,
      312,  311,  295,  310,  343,  343,  343,  343,  343,  343,
      354,  354,  354,  354,  309,  308,  307,  306,  354,  354,
      354,  354,  305,  304,  303,  302,  354,  354,  354,  354,
      354,  354,  362,  362,  362,  362,  301,  300,  299,  298,

      362,  362,  362,  362,  297,  291,  290,  289,  362,  362,
      362,  362,  362,  362,  342,  342,  342,  342,  288,  287,
      286,  285,  342,  342,  342,  342,  284,  283,  282,  281,
      342,  342,  342,  342,  342,  342,   46,   46,   46,   46,
       46,   50,   50,   50,   50,   50,   58,   58,   58,   58,
       58,   62,  280,   62,   66,   66,   66,  279,   66,  152,
      278,  152,  152,  152,  208,  208,  293,  293,  293,  293,
      293,  321,  321,  321,  321,  321,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  257,  255,  254,  253,  252,  251,

      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  212,  211,  145,  202,  201,
      193,  192,  191,  190,  189,  188,  187,  184,  183,  182,
      181,  180,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  163,  162,  161,  160,  157,  151,
      150,  145,  136,  135,  134,  133,  130,  129,  121,  114,
       95,   94,   91,   68,   67,   63,   61,   57,  371,    7,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371
    } ;

static yyconst short int yy_chk[749] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,    6,    9,    9,    9,   12,   16,    3,    4,
        5,    6,    3,    4,    5,    6,   10,   10,   10,   20,
       16,   21,   22,   22,   22,   45,   23,   58,   20,   21,
       23,  384,   12,   26,   26,   31,   23,   31,   22,   22,

       22,   22,   28,   28,   31,   32,   34,   33,   56,   56,
       56,   35,   32,   58,   42,   32,   33,   34,   32,   35,
       45,   35,   42,   80,   35,  138,   22,   24,   36,   24,
       24,   24,   24,   38,   36,   36,   54,   38,   24,   24,
       24,   24,   24,   39,   55,   54,  138,   80,   24,   24,
       24,   38,   61,   61,   61,   24,  139,   55,   39,   60,
      382,   39,   73,   73,   73,   55,   24,   25,  119,   25,
       25,   25,   25,  119,   60,   60,   60,  139,   25,   25,
       25,   25,  137,   41,   67,   93,   93,  380,   25,   25,
       25,  137,   67,   41,   41,   25,   41,  203,   41,   67,

       67,   67,   79,   79,   79,   79,   73,  128,   60,   83,
       83,   99,   99,   83,   83,   83,   83,  113,  113,  127,
      129,  177,  129,  203,  177,  128,  127,  378,  368,  128,
      367,  257,  144,   67,   74,   74,   74,   74,  141,  154,
      154,  154,  154,   74,   74,   74,  144,  144,  144,  144,
      141,  141,  141,   74,   74,   74,   81,  257,   81,   81,
       81,   81,  142,  146,  141,  366,  365,   81,   81,   81,
      146,  146,  146,  147,  142,  142,  142,   81,   81,   81,
      147,  147,  147,  156,  361,  359,  149,  149,  142,  143,
      149,  149,  149,  149,  211,  211,  211,  156,  259,  259,

      259,  143,  143,  143,  143,  155,  155,  155,  155,  143,
      143,  143,  143,  356,  155,  143,  155,  143,  143,  143,
      143,  143,  143,  355,  155,  206,  155,  204,  204,  204,
      204,  209,  209,  209,  209,  204,  204,  204,  204,  206,
      206,  206,  206,  204,  204,  204,  204,  204,  204,  207,
      210,  210,  210,  210,  353,  351,  207,  207,  207,  210,
      293,  210,  350,  349,  348,  347,  346,  341,  340,  210,
      339,  210,  256,  256,  256,  256,  338,  337,  334,  333,
      256,  256,  256,  256,  295,  332,  293,  328,  256,  256,
      256,  256,  256,  256,  292,  292,  292,  292,  342,  295,

      295,  295,  292,  292,  292,  292,  323,  326,  321,  324,
      292,  292,  292,  292,  292,  292,  320,  319,  323,  323,
      323,  324,  324,  324,  342,  318,  316,  311,  310,  309,
      307,  306,  323,  295,  304,  324,  325,  303,  302,  300,
      299,  298,  297,  294,  291,  289,  288,  287,  325,  325,
      325,  325,  286,  285,  283,  281,  325,  325,  325,  325,
      280,  279,  325,  278,  325,  325,  325,  325,  325,  325,
      343,  343,  343,  343,  277,  276,  275,  274,  343,  343,
      343,  343,  273,  272,  270,  268,  343,  343,  343,  343,
      343,  343,  354,  354,  354,  354,  267,  266,  265,  261,

      354,  354,  354,  354,  260,  255,  254,  253,  354,  354,
      354,  354,  354,  354,  362,  362,  362,  362,  250,  249,
      247,  246,  362,  362,  362,  362,  245,  244,  243,  242,
      362,  362,  362,  362,  362,  362,  372,  372,  372,  372,
      372,  373,  373,  373,  373,  373,  374,  374,  374,  374,
      374,  375,  241,  375,  376,  376,  376,  240,  376,  377,
      239,  377,  377,  377,  379,  379,  381,  381,  381,  381,
      381,  383,  383,  383,  383,  383,  238,  236,  234,  233,
      232,  231,  230,  229,  228,  227,  225,  224,  223,  222,
      220,  217,  216,  215,  205,  202,  201,  200,  199,  197,

      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  181,  180,  179,  178,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  151,  150,  148,  140,  130,
      126,  125,  124,  123,  122,  121,  120,  118,  117,  116,
      115,  114,  112,  110,  109,  108,  107,  106,  105,  104,
      103,  102,  101,  100,   98,   97,   96,   95,   89,   76,
       75,   66,   53,   52,   49,   48,   44,   43,   40,   37,
       30,   29,   27,   19,   17,   15,   13,   11,    7,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
// Copyright (c) 1995  David Engberg  All rights reserved
// $Id: lexer.l,v 1.11 1997/11/10 00:48:06 geppetto Exp $
 #include <string>
 #include <cstdio>
 #include <cctype>
 #include <stream.h>
 #include "unicode_string.h"
 #include "parser_decls.h"
 #include "parser.h"

 YY_BUFFER_STATE gInputBuffer;

 unicode_string LexStringToUnicode(const char* inputString);
 bool ParseLong(const char* inputString, unsigned short base,
		unsigned long long& result);
 bool ParseInt(const char* inputString, unsigned short base,
	       unsigned long& result);

 bool yydeprecated;
#define YY_NEVER_INTERACTIVE 1
#define INCOMMENT 1

#define JAVACOMMENT 2

/*
 * The {DIGIT}+ part of both of these is contrary to the written spec, but
 * their compiler accepts 0f as a valid float literal, so I needed to add this
 * for compatibility.
 */
/* haven't dealt with their Unicode scheme yet. */
/* This is a little hack to allow C preprocessor line number directives */
/* Another little hack to support @deprecated tags in comments */
#line 746 "lexer.C"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 68 "lexer.l"


#line 899 "lexer.C"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 690 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 70 "lexer.l"
{ yylineno = ::atoi(yytext + 2); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "lexer.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "lexer.l"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "lexer.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "lexer.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "lexer.l"
{ yydeprecated = true; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "lexer.l"
;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "lexer.l"
;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "lexer.l"
{ BEGIN(INCOMMENT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "lexer.l"
;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "lexer.l"
{ BEGIN(JAVACOMMENT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "lexer.l"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "lexer.l"
;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "lexer.l"
{
                  yytext[yyleng - 1] = '\0';
                  if (!::ParseLong(yytext, 10, yylval.doubleLong)) {
		    ::yyerror("Numeric overflow.");
                  }
		  return(LONG_LITERAL);
                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 "lexer.l"
{
                  yytext[yyleng - 1] = '\0';
                  if (!::ParseLong(yytext + 2, 16, yylval.doubleLong)) {
                    ::yyerror("Numeric overflow.");
                  }
		  return(LONG_LITERAL);
                }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 100 "lexer.l"
{
                  yytext[yyleng - 1] = '\0';
                  if (!::ParseLong(yytext + 1, 8, yylval.doubleLong)) {
		    ::yyerror("Numeric overflow.");
                  }
		  return(LONG_LITERAL);
                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 107 "lexer.l"
{
                  if (!::ParseInt(yytext, 10, yylval.longNumber)) {
		    ::yyerror("Numeric overflow.");
		  }
		  return(INT_LITERAL);
                }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 113 "lexer.l"
{
                  if (!::ParseInt(yytext + 2, 16, yylval.longNumber)) {
		    ::yyerror("Numeric overflow.");
                  }
		  return(INT_LITERAL);
                }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 119 "lexer.l"
{
                  if (!::ParseInt(yytext + 1, 8, yylval.longNumber)) {
		    ::yyerror("Numeric overflow.");
                  }
		  return(INT_LITERAL);
                }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "lexer.l"
{ yytext[yyleng - 1] = '\0';
                  unicode_string tempString = ::LexStringToUnicode(yytext + 1);
		  if (tempString.length() > 0) {
		    yylval.longNumber = tempString[tempString.length() - 1];
		    return(CHARACTER_LITERAL);
		  } else {
		    ::yyerror("Invalid character literal.");
		  }
                }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 134 "lexer.l"
{ yylval.floatNumber = ::atof(yytext); return(FLOAT_LITERAL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "lexer.l"
{ yylval.doubleFloat = ::atof(yytext);
                  return(DOUBLE_LITERAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 137 "lexer.l"
{ yytext[yyleng - 1] = '\0';
                  yylval.text =
                     new unicode_string(::LexStringToUnicode(yytext + 1));
                  yytext[yyleng] = '"';   // restore it, just in case
                  return(STRING_LITERAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return(ABSTRACT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return(BOOLEAN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return(BREAK); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return(BYTE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return(CASE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return(CATCH); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return(CHAR); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return(CLASS); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return(CONTINUE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return(DEFAULT ); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return(DO); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return(DOUBLE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return(ELSE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return(EXTENDS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return(FALSE_TOKEN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return(FINAL); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return(FINALLY); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return(FLOAT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return(FOR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return(IF); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return(IMPLEMENTS ); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return(IMPORT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return(INSTANCEOF); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return(INT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return(INTERFACE); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return(LONG); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return(NATIVE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return(NEW); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return(NULL_TOKEN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return(PACKAGE ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return(PRIVATE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return(PROTECTED); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return(PUBLIC); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return(RETURN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 176 "lexer.l"
{ return(SHORT); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 177 "lexer.l"
{ return(STATIC); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return(SUPER); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return(SWITCH); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 180 "lexer.l"
{ return(SYNCHRONIZED ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 181 "lexer.l"
{ return(THIS); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 182 "lexer.l"
{ return(VOLATILE); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 183 "lexer.l"
{ return(THROW); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 184 "lexer.l"
{ return(THROWS); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 185 "lexer.l"
{ return(TRANSIENT); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 186 "lexer.l"
{ return(TRUE_TOKEN); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 187 "lexer.l"
{ return(TRY); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 188 "lexer.l"
{ return(VOID); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 189 "lexer.l"
{ return(WHILE ); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 190 "lexer.l"
{ return(DOTNEW); }   // ugly hack for non-LALR grammar
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 191 "lexer.l"
{ return(SHIFT_RIGHT_EQUALS); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 192 "lexer.l"
{ return(FILL_SHIFT_RIGHT_EQUALS); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 193 "lexer.l"
{ return(SHIFT_LEFT_EQUALS); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 194 "lexer.l"
{ return(ADD_EQUALS); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 195 "lexer.l"
{ return(SUB_EQUALS); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 196 "lexer.l"
{ return(MUL_EQUALS); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 197 "lexer.l"
{ return(DIV_EQUALS); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 198 "lexer.l"
{ return(MOD_EQUALS); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 199 "lexer.l"
{ return(AND_EQUALS); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 200 "lexer.l"
{ return(XOR_EQUALS); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 201 "lexer.l"
{ return(OR_EQUALS); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 202 "lexer.l"
{ return(BITSHIFT_RIGHT); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 203 "lexer.l"
{ return(FILL_SHIFT_RIGHT); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 204 "lexer.l"
{ return(SHIFT_LEFT); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 205 "lexer.l"
{ return(INCR); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 206 "lexer.l"
{ return(DECR); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 207 "lexer.l"
{ return(AND); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 208 "lexer.l"
{ return(OR); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 209 "lexer.l"
{ return(LTEQ); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 210 "lexer.l"
{ return(GTEQ); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 211 "lexer.l"
{ return(EQUAL_COMPARE); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 212 "lexer.l"
{ return(NOT_EQUAL); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 213 "lexer.l"
{ return(*yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 214 "lexer.l"
{ yylval.text =
                     new unicode_string(::LexStringToUnicode(yytext));
                  return(SYMBOL); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 217 "lexer.l"
{ yylval.longNumber = *yytext;  return(ERROR); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 219 "lexer.l"
ECHO;
	YY_BREAK
#line 1539 "lexer.C"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(INCOMMENT):
			case YY_STATE_EOF(JAVACOMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 371);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 219 "lexer.l"


void
InitializeLexer(const string& tokenizeString)
{
  yylineno = 1;
  const char* inputBytes = tokenizeString.c_str();
  gInputBuffer = yy_scan_bytes(inputBytes, tokenizeString.length());
}

void
FinishLexer()
{
  yy_delete_buffer(gInputBuffer);
}

unicode_string
LexStringToUnicode(const char* inputString) {
  unicode_string tempString;
  while (*inputString != '\0') {
    unsigned short characterValue = 0;
    if (*inputString == '\\') {
      switch (inputString[1]) {
        case '0': case '1': case '2': case '3':
	case '4': case '5': case '6': case '7':
          characterValue = inputString[1] - '0';
	  if (inputString[2] >= '0' && inputString[2] <= '9') {
	    characterValue *= 8;
	    characterValue += inputString[2] - '0';
	    ++inputString;
	  }
	  if ((*(inputString - 2) <= '3') &&
	      (inputString[2] >= '0' && inputString[2] <= '9')) {
	    characterValue *= 8;
	    characterValue += inputString[2] - '0';
	    ++inputString;
	  }
	  tempString += characterValue;
	  break;
	case 'u':
	  if (isxdigit(inputString[2]) && isxdigit(inputString[3]) &&
	      isxdigit(inputString[4]) && isxdigit(inputString[5])) {
	    char hexBuffer[5];
	    ::strncpy(hexBuffer, inputString + 2, 4);
	    tempString += (unicode_char)::strtol(hexBuffer, 0, 16);
	    inputString += 4;
	  } else {
	    tempString += 0x5c;
	  }
	  break;
	case 'b':
	  tempString += 0x8;
	  break;
	case 't':
	  tempString += 0x9;
	  break;
	case 'n':
	  tempString += 0xa;
	  break;
	case 'f':
	  tempString += 0xc;
          break;
        case 'r':
          tempString += 0xd;
	  break;
	case '"':
          tempString += 0x22;
          break;
        case '\'':
          tempString += 0x27;
          break;
        case '\\':
          tempString += 0x5c;
          break;
        default:
          tempString += 0x5c;
      }
      ++inputString;
    } else {
      unsigned char inputChar = *inputString;
      tempString += (unicode_string::value_type)inputChar;
    }
    inputString++;
  }
  return tempString;
}

bool
ParseLong(const char* inputString, unsigned short base,
	  unsigned long long& result) {
  result = 0;
  for (; *inputString != 0; ++inputString) {
    unsigned long adder;
    if (*inputString >= '0' && *inputString <= '9') {
      adder = *inputString - '0';
    } else if (*inputString >= 'a' && *inputString <= 'z') {
      adder = (*inputString - 'a') + 10;
    } else if (*inputString >= 'A' && *inputString <= 'Z') {
      adder = (*inputString - 'A') + 10;
    }
    unsigned long long sum = result * base + adder;
    if (sum < result) {
      return false;
    }
    result = sum;
  }
  return true;
}

bool
ParseInt(const char* inputString, unsigned short base,
	 unsigned long& result) {
  result = 0;
  for (; *inputString != 0; ++inputString) {
    unsigned long adder;
    if (*inputString >= '0' && *inputString <= '9') {
      adder = *inputString - '0';
    } else if (*inputString >= 'a' && *inputString <= 'z') {
      adder = (*inputString - 'a') + 10;
    } else if (*inputString >= 'A' && *inputString <= 'Z') {
      adder = (*inputString - 'A') + 10;
    }
    unsigned long sum = result * base + adder;
    if (sum < result) {
      return false;
    }
    result = sum;
  }
  return true;;
}
